//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura {
            get {
                object obj = ResourceManager.GetObject("costura", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_antire_runtime_dll {
            get {
                object obj = ResourceManager.GetObject("costura_antire_runtime_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_bouncycastle_crypto_dll {
            get {
                object obj = ResourceManager.GetObject("costura_bouncycastle_crypto_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_bunifu_licensing_dll {
            get {
                object obj = ResourceManager.GetObject("costura_bunifu_licensing_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_bunifu_ui_winforms_1_5_3_dll {
            get {
                object obj = ResourceManager.GetObject("costura_bunifu_ui_winforms_1_5_3_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_bunifu_ui_winforms_bunifubutton_dll {
            get {
                object obj = ResourceManager.GetObject("costura_bunifu_ui_winforms_bunifubutton_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_bunifu_ui_winforms_bunifucheckbox_dll {
            get {
                object obj = ResourceManager.GetObject("costura_bunifu_ui_winforms_bunifucheckbox_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_bunifu_ui_winforms_bunifucircleprogress_dll {
            get {
                object obj = ResourceManager.GetObject("costura_bunifu_ui_winforms_bunifucircleprogress_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_bunifu_ui_winforms_bunifucolortransition_dll {
            get {
                object obj = ResourceManager.GetObject("costura_bunifu_ui_winforms_bunifucolortransition_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_bunifu_ui_winforms_bunifudatagridview_dll {
            get {
                object obj = ResourceManager.GetObject("costura_bunifu_ui_winforms_bunifudatagridview_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_bunifu_ui_winforms_bunifudatepicker_dll {
            get {
                object obj = ResourceManager.GetObject("costura_bunifu_ui_winforms_bunifudatepicker_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_bunifu_ui_winforms_bunifudropdown_dll {
            get {
                object obj = ResourceManager.GetObject("costura_bunifu_ui_winforms_bunifudropdown_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_bunifu_ui_winforms_bunifuformdock_dll {
            get {
                object obj = ResourceManager.GetObject("costura_bunifu_ui_winforms_bunifuformdock_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_bunifu_ui_winforms_bunifugauge_dll {
            get {
                object obj = ResourceManager.GetObject("costura_bunifu_ui_winforms_bunifugauge_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_bunifu_ui_winforms_bunifugradientpanel_dll {
            get {
                object obj = ResourceManager.GetObject("costura_bunifu_ui_winforms_bunifugradientpanel_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_bunifu_ui_winforms_bunifugroupbox_dll {
            get {
                object obj = ResourceManager.GetObject("costura_bunifu_ui_winforms_bunifugroupbox_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_bunifu_ui_winforms_bunifuimagebutton_dll {
            get {
                object obj = ResourceManager.GetObject("costura_bunifu_ui_winforms_bunifuimagebutton_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_bunifu_ui_winforms_bunifulabel_dll {
            get {
                object obj = ResourceManager.GetObject("costura_bunifu_ui_winforms_bunifulabel_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_bunifu_ui_winforms_bunifuloader_dll {
            get {
                object obj = ResourceManager.GetObject("costura_bunifu_ui_winforms_bunifuloader_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_bunifu_ui_winforms_bunifupages_dll {
            get {
                object obj = ResourceManager.GetObject("costura_bunifu_ui_winforms_bunifupages_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_bunifu_ui_winforms_bunifupanel_dll {
            get {
                object obj = ResourceManager.GetObject("costura_bunifu_ui_winforms_bunifupanel_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_bunifu_ui_winforms_bunifupicturebox_dll {
            get {
                object obj = ResourceManager.GetObject("costura_bunifu_ui_winforms_bunifupicturebox_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_bunifu_ui_winforms_bunifuprogressbar_dll {
            get {
                object obj = ResourceManager.GetObject("costura_bunifu_ui_winforms_bunifuprogressbar_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_bunifu_ui_winforms_bunifuradiobutton_dll {
            get {
                object obj = ResourceManager.GetObject("costura_bunifu_ui_winforms_bunifuradiobutton_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_bunifu_ui_winforms_bunifurating_dll {
            get {
                object obj = ResourceManager.GetObject("costura_bunifu_ui_winforms_bunifurating_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_bunifu_ui_winforms_bunifuscrollbar_dll {
            get {
                object obj = ResourceManager.GetObject("costura_bunifu_ui_winforms_bunifuscrollbar_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_bunifu_ui_winforms_bunifuseparator_dll {
            get {
                object obj = ResourceManager.GetObject("costura_bunifu_ui_winforms_bunifuseparator_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_bunifu_ui_winforms_bunifushadowpanel_dll {
            get {
                object obj = ResourceManager.GetObject("costura_bunifu_ui_winforms_bunifushadowpanel_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_bunifu_ui_winforms_bunifushapes_dll {
            get {
                object obj = ResourceManager.GetObject("costura_bunifu_ui_winforms_bunifushapes_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_bunifu_ui_winforms_bunifuslider_dll {
            get {
                object obj = ResourceManager.GetObject("costura_bunifu_ui_winforms_bunifuslider_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_bunifu_ui_winforms_bunifusnackbar_dll {
            get {
                object obj = ResourceManager.GetObject("costura_bunifu_ui_winforms_bunifusnackbar_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_bunifu_ui_winforms_bunifutextbox_dll {
            get {
                object obj = ResourceManager.GetObject("costura_bunifu_ui_winforms_bunifutextbox_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_bunifu_ui_winforms_bunifutoggleswitch_dll {
            get {
                object obj = ResourceManager.GetObject("costura_bunifu_ui_winforms_bunifutoggleswitch_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_bunifu_ui_winforms_bunifutooltip_dll {
            get {
                object obj = ResourceManager.GetObject("costura_bunifu_ui_winforms_bunifutooltip_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_bunifu_ui_winforms_bunifutransition_dll {
            get {
                object obj = ResourceManager.GetObject("costura_bunifu_ui_winforms_bunifutransition_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_bunifu_ui_winforms_bunifuusercontrol_dll {
            get {
                object obj = ResourceManager.GetObject("costura_bunifu_ui_winforms_bunifuusercontrol_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_bunifu_ui_winforms_deprecated_dll {
            get {
                object obj = ResourceManager.GetObject("costura_bunifu_ui_winforms_deprecated_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_cgeoip_dll {
            get {
                object obj = ResourceManager.GetObject("costura_cgeoip_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_costura_dll {
            get {
                object obj = ResourceManager.GetObject("costura_costura_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_costura_pdb {
            get {
                object obj = ResourceManager.GetObject("costura_costura_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_customcontrols_dll {
            get {
                object obj = ResourceManager.GetObject("costura_customcontrols_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_customcontrols_pdb {
            get {
                object obj = ResourceManager.GetObject("costura_customcontrols_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_discord_net_commands_dll {
            get {
                object obj = ResourceManager.GetObject("costura_discord_net_commands_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_discord_net_core_dll {
            get {
                object obj = ResourceManager.GetObject("costura_discord_net_core_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_discord_net_rest_dll {
            get {
                object obj = ResourceManager.GetObject("costura_discord_net_rest_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_discord_net_webhook_dll {
            get {
                object obj = ResourceManager.GetObject("costura_discord_net_webhook_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_discord_net_websocket_dll {
            get {
                object obj = ResourceManager.GetObject("costura_discord_net_websocket_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_dnlib_dll {
            get {
                object obj = ResourceManager.GetObject("costura_dnlib_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_fastcoloredtextbox_dll {
            get {
                object obj = ResourceManager.GetObject("costura_fastcoloredtextbox_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_guna_ui2_dll {
            get {
                object obj = ResourceManager.GetObject("costura_guna_ui2_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_iconextractor_dll {
            get {
                object obj = ResourceManager.GetObject("costura_iconextractor_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_microsoft_bcl_asyncinterfaces_dll {
            get {
                object obj = ResourceManager.GetObject("costura_microsoft_bcl_asyncinterfaces_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_microsoft_win32_primitives_dll {
            get {
                object obj = ResourceManager.GetObject("costura_microsoft_win32_primitives_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_mono_cecil_dll {
            get {
                object obj = ResourceManager.GetObject("costura_mono_cecil_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_mono_cecil_mdb_dll {
            get {
                object obj = ResourceManager.GetObject("costura_mono_cecil_mdb_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_mono_cecil_pdb_dll {
            get {
                object obj = ResourceManager.GetObject("costura_mono_cecil_pdb_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_mono_cecil_rocks_dll {
            get {
                object obj = ResourceManager.GetObject("costura_mono_cecil_rocks_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_mono_httputility_dll {
            get {
                object obj = ResourceManager.GetObject("costura_mono_httputility_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_mono_nat_dll {
            get {
                object obj = ResourceManager.GetObject("costura_mono_nat_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_netstandard_dll {
            get {
                object obj = ResourceManager.GetObject("costura_netstandard_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_newtonsoft_json_dll {
            get {
                object obj = ResourceManager.GetObject("costura_newtonsoft_json_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_pinvoke_kernel32_dll {
            get {
                object obj = ResourceManager.GetObject("costura_pinvoke_kernel32_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_pinvoke_shell32_dll {
            get {
                object obj = ResourceManager.GetObject("costura_pinvoke_shell32_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_pinvoke_windows_core_dll {
            get {
                object obj = ResourceManager.GetObject("costura_pinvoke_windows_core_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_protobuf_net_dll {
            get {
                object obj = ResourceManager.GetObject("costura_protobuf_net_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_server_dll {
            get {
                object obj = ResourceManager.GetObject("costura_server_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_server_pdb {
            get {
                object obj = ResourceManager.GetObject("costura_server_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_sharpupdate_dll {
            get {
                object obj = ResourceManager.GetObject("costura_sharpupdate_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_sharpupdate_pdb {
            get {
                object obj = ResourceManager.GetObject("costura_sharpupdate_pdb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_siticone_ui_dll {
            get {
                object obj = ResourceManager.GetObject("costura_siticone_ui_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_appcontext_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_appcontext_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_buffers_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_buffers_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_collections_concurrent_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_collections_concurrent_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_collections_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_collections_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_collections_immutable_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_collections_immutable_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_collections_nongeneric_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_collections_nongeneric_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_collections_specialized_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_collections_specialized_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_componentmodel_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_componentmodel_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_componentmodel_eventbasedasync_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_componentmodel_eventbasedasync_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_componentmodel_primitives_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_componentmodel_primitives_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_componentmodel_typeconverter_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_componentmodel_typeconverter_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_console_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_console_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_data_common_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_data_common_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_diagnostics_contracts_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_diagnostics_contracts_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_diagnostics_debug_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_diagnostics_debug_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_diagnostics_diagnosticsource_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_diagnostics_diagnosticsource_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_diagnostics_fileversioninfo_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_diagnostics_fileversioninfo_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_diagnostics_process_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_diagnostics_process_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_diagnostics_stacktrace_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_diagnostics_stacktrace_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_diagnostics_textwritertracelistener_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_diagnostics_textwritertracelistener_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_diagnostics_tools_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_diagnostics_tools_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_diagnostics_tracesource_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_diagnostics_tracesource_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_diagnostics_tracing_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_diagnostics_tracing_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_drawing_primitives_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_drawing_primitives_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_dynamic_runtime_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_dynamic_runtime_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_globalization_calendars_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_globalization_calendars_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_globalization_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_globalization_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_globalization_extensions_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_globalization_extensions_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_interactive_async_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_interactive_async_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_io_compression_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_io_compression_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_io_compression_zipfile_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_io_compression_zipfile_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_io_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_io_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_io_filesystem_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_io_filesystem_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_io_filesystem_driveinfo_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_io_filesystem_driveinfo_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_io_filesystem_primitives_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_io_filesystem_primitives_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_io_filesystem_watcher_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_io_filesystem_watcher_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_io_isolatedstorage_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_io_isolatedstorage_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_io_memorymappedfiles_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_io_memorymappedfiles_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_io_pipes_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_io_pipes_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_io_unmanagedmemorystream_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_io_unmanagedmemorystream_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_linq_async_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_linq_async_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_linq_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_linq_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_linq_expressions_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_linq_expressions_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_linq_parallel_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_linq_parallel_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_linq_queryable_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_linq_queryable_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_memory_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_memory_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_net_http_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_net_http_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_net_nameresolution_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_net_nameresolution_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_net_networkinformation_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_net_networkinformation_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_net_ping_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_net_ping_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_net_primitives_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_net_primitives_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_net_requests_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_net_requests_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_net_security_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_net_security_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_net_sockets_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_net_sockets_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_net_webheadercollection_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_net_webheadercollection_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_net_websockets_client_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_net_websockets_client_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_net_websockets_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_net_websockets_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_numerics_vectors_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_numerics_vectors_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_objectmodel_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_objectmodel_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_reflection_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_reflection_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_reflection_extensions_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_reflection_extensions_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_reflection_primitives_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_reflection_primitives_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_resources_reader_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_resources_reader_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_resources_resourcemanager_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_resources_resourcemanager_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_resources_writer_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_resources_writer_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_runtime_compilerservices_unsafe_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_runtime_compilerservices_unsafe_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_runtime_compilerservices_visualc_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_runtime_compilerservices_visualc_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_runtime_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_runtime_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_runtime_extensions_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_runtime_extensions_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_runtime_handles_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_runtime_handles_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_runtime_interopservices_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_runtime_interopservices_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_runtime_interopservices_runtimeinformation_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_runtime_interopservices_runtimeinformation_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_runtime_numerics_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_runtime_numerics_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_runtime_serialization_formatters_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_runtime_serialization_formatters_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_runtime_serialization_json_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_runtime_serialization_json_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_runtime_serialization_primitives_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_runtime_serialization_primitives_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_runtime_serialization_xml_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_runtime_serialization_xml_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_security_claims_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_security_claims_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_security_cryptography_algorithms_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_security_cryptography_algorithms_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_security_cryptography_csp_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_security_cryptography_csp_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_security_cryptography_encoding_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_security_cryptography_encoding_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_security_cryptography_primitives_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_security_cryptography_primitives_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_security_cryptography_x509certificates_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_security_cryptography_x509certificates_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_security_principal_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_security_principal_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_security_securestring_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_security_securestring_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_text_encoding_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_text_encoding_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_text_encoding_extensions_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_text_encoding_extensions_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_text_regularexpressions_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_text_regularexpressions_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_threading_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_threading_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_threading_overlapped_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_threading_overlapped_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_threading_tasks_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_threading_tasks_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_threading_tasks_extensions_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_threading_tasks_extensions_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_threading_tasks_parallel_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_threading_tasks_parallel_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_threading_thread_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_threading_thread_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_threading_threadpool_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_threading_threadpool_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_threading_timer_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_threading_timer_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_valuetuple_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_valuetuple_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_xml_readerwriter_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_xml_readerwriter_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_xml_xdocument_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_xml_xdocument_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_xml_xmldocument_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_xml_xmldocument_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_xml_xmlserializer_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_xml_xmlserializer_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_xml_xpath_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_xml_xpath_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_system_xml_xpath_xdocument_dll {
            get {
                object obj = ResourceManager.GetObject("costura_system_xml_xpath_xdocument_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] costura_vestris_resourcelib_dll {
            get {
                object obj = ResourceManager.GetObject("costura_vestris_resourcelib_dll", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] custom_alert_notifications_alert {
            get {
                object obj = ResourceManager.GetObject("custom_alert_notifications_alert", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] InputDialog {
            get {
                object obj = ResourceManager.GetObject("InputDialog", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Forms_FormAbout {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Forms_FormAbout", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Forms_FormAudio {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Forms_FormAudio", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Forms_FormBlockClients {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Forms_FormBlockClients", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Forms_FormBuilder {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Forms_FormBuilder", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Forms_FormCertificate {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Forms_FormCertificate", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Forms_FormChat {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Forms_FormChat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Forms_FormDOS {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Forms_FormDOS", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Forms_FormDownloadFile {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Forms_FormDownloadFile", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Forms_FormFileManager {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Forms_FormFileManager", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Forms_FormFileSearcher {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Forms_FormFileSearcher", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Forms_FormFun {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Forms_FormFun", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Forms_FormKeylogger {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Forms_FormKeylogger", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Forms_FormMiner {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Forms_FormMiner", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Forms_FormNetstat {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Forms_FormNetstat", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Forms_FormPorts {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Forms_FormPorts", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Forms_FormPowerShell {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Forms_FormPowerShell", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Forms_FormProcessManager {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Forms_FormProcessManager", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Forms_FormRegistryEditor {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Forms_FormRegistryEditor", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Forms_FormRegValueEditBinary {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Forms_FormRegValueEditBinary", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Forms_FormRegValueEditMultiString {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Forms_FormRegValueEditMultiString", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Forms_FormRegValueEditString {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Forms_FormRegValueEditString", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Forms_FormRegValueEditWord {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Forms_FormRegValueEditWord", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Forms_FormRemoteDesktop {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Forms_FormRemoteDesktop", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Forms_FormSetting {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Forms_FormSetting", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Forms_FormShell {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Forms_FormShell", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Forms_FormWebcam {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Forms_FormWebcam", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Forms_FrmAngry {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Forms_FrmAngry", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Forms_FrmCSPM {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Forms_FrmCSPM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Forms_FrmDiscordST3 {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Forms_FrmDiscordST3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Forms_FrmEmailer {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Forms_FrmEmailer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Forms_FrmInfo {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Forms_FrmInfo", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Forms_FrmNoStub {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Forms_FrmNoStub", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Forms_FrmReco {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Forms_FrmReco", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Forms_FrmSkynet {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Forms_FrmSkynet", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Forms_FrmWebHookSPM {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Forms_FrmWebHookSPM", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Forms_Login {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Forms_Login", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Forms_PEGASUSMain {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Forms_PEGASUSMain", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Forms_Register {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Forms_Register", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Forms_Remote_Desktop {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Forms_Remote_Desktop", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Forms_Remote_hVNC {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Forms_Remote_hVNC", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Forms_Splashes {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Forms_Splashes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Forms_Welcome {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Forms_Welcome", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_FormSendFileToMemory {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_FormSendFileToMemory", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_FrmSplash {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_FrmSplash", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_FULL_VERSION_exe {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_FULL_VERSION_exe", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_PegasusBytes_DarkBytes {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_PegasusBytes_DarkBytes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_PegasusBytes_PegasusBytes {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_PegasusBytes_PegasusBytes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Properties_Resources {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Properties_Resources", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_RhVNC_Connections {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_RhVNC_Connections", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_Tools_Plugin_RemotehVNC {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_Tools_Plugin_RemotehVNC", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] PEGASUS_VNCForm {
            get {
                object obj = ResourceManager.GetObject("PEGASUS_VNCForm", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
